spring:
  application:
    name: freefirebot
bot:
  token: ${8971375818:AAFiLVlkvi3eno82qsztoeHfnAYOEX-42qY}
  username: ${@ffplyerinfo_bot}

freefire:
  api:
    player-info-url: https://freefire-api-six.vercel.app
    ban-check-url: https://ff.garena.com/api/antihack/check_banned
